apiVersion: v1
kind: Service
metadata:
  name: mythical-mysfits-eks
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mythical-mysfits-eks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythical-mysfits-eks
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mythical-mysfits-eks
  template:
    metadata:
      labels:
        app: mythical-mysfits-eks
    spec:
      containers:
        - name: mythical-mysfits-eks
          image: 432812493780.dkr.ecr.us-west-2.amazonaws.com/mythic-mono-xe5o8c97txgl:latest
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          env:
            - name: DDB_TABLE_NAME
              value: Table-mythical-mysfits-containers











